### PR TITLE
188_workaround for test cases to run without session exception

### PR DESCRIPTION
**Pull request by MalgorzataDzienia**
1. Sesion exception BROWSER_TIMEOUT is fixed by using in selenium tests the right structure of test case which inherit BaseTest and test page which inherit BasePage.
2. There is no need to close driver in the test case, because it is done automatically in framework.
3. This is quick fix, the refactoring of test cases is planned to be done with review tasks which are assigned to @MajPat .

### CODE REVIEW

**Review by tompalka — APPROVED** [review]
This is a little confusing that just adding not used page object as member in the test fixes SessionTimeout issue. But as we're planning to refactor this code and marked class to be removed after refactor, it is temporary solution. Just to be sure - please add to `QuickFixSeleniumPage` comments which issue is going to remove this class.

**Comment by tompalka** [comment]
@przwojtkow @pawel-szczesny @lstefaniszyn Please take a look and merge it if you find everything ok

**Comment by MalgorzataDzienia** [comment]
> This is a little confusing that just adding not used page object as member in the test fixes SessionTimeout issue. But as we're planning to refactor this code and marked class to be removed after refactor, it is temporary solution. Just to be sure - please add to `QuickFixSeleniumPage` comments which issue is going to remove this class.

There is a comment in QuickFixSeleniumPage 
See the file:

public class QuickFixSeleniumPage extends BasePage {
    //This page is created to fix Selenium Session Exception from tes.WebElements test cases.
    //When the test cases are refactored, this page should be deleted.

**Comment by tompalka** [comment]
> > This is a little confusing that just adding not used page object as member in the test fixes SessionTimeout issue. But as we're planning to refactor this code and marked class to be removed after refactor, it is temporary solution. Just to be sure - please add to `QuickFixSeleniumPage` comments which issue is going to remove this class.
> 
> There is a comment in QuickFixSeleniumPage
> See the file:
> 
> public class QuickFixSeleniumPage extends BasePage {
> //This page is created to fix Selenium Session Exception from tes.WebElements test cases.
> //When the test cases are refactored, this page should be deleted.

I meant to add issue number in the comment. I saw that there is a comment which actually explains a lot.

**Review by pawel-szczesny — APPROVED** [review]
I'm approving but I agree that it should be refactored. 
@MalgorzataDzienia Can you provide link to created task for refactor?
After that please merge this PR.

**Comment by MalgorzataDzienia** [comment]
> I'm approving but I agree that it should be refactored.
> @MalgorzataDzienia Can you provide link to created task for refactor?
> After that please merge this PR.

Issue created
https://github.com/devonfw-forge/mrchecker-source/issues/18

**Pull request merged**
